/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as TemplatesIndexImport } from "./routes/templates/index";
import { Route as StatementsIndexImport } from "./routes/statements/index";
import { Route as IncidentsIndexImport } from "./routes/incidents/index";
import { Route as StatementsNewRouteImport } from "./routes/statements/new/route";
import { Route as IncidentsNewRouteImport } from "./routes/incidents/new/route";
import { Route as StatementsNewIndexImport } from "./routes/statements/new/index";
import { Route as IncidentsNewIndexImport } from "./routes/incidents/new/index";
import { Route as StatementsNewStatementImport } from "./routes/statements/new/statement";
import { Route as StatementsNewReviewImport } from "./routes/statements/new/review";
import { Route as StatementsNewDetailsImport } from "./routes/statements/new/details";
import { Route as StatementsNewConsentImport } from "./routes/statements/new/consent";
import { Route as IncidentsDateIncidentIdImport } from "./routes/incidents/$date/$incidentId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const TemplatesIndexRoute = TemplatesIndexImport.update({
  id: "/templates/",
  path: "/templates/",
  getParentRoute: () => rootRoute,
} as any);

const StatementsIndexRoute = StatementsIndexImport.update({
  id: "/statements/",
  path: "/statements/",
  getParentRoute: () => rootRoute,
} as any);

const IncidentsIndexRoute = IncidentsIndexImport.update({
  id: "/incidents/",
  path: "/incidents/",
  getParentRoute: () => rootRoute,
} as any);

const StatementsNewRouteRoute = StatementsNewRouteImport.update({
  id: "/statements/new",
  path: "/statements/new",
  getParentRoute: () => rootRoute,
} as any);

const IncidentsNewRouteRoute = IncidentsNewRouteImport.update({
  id: "/incidents/new",
  path: "/incidents/new",
  getParentRoute: () => rootRoute,
} as any);

const StatementsNewIndexRoute = StatementsNewIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => StatementsNewRouteRoute,
} as any);

const IncidentsNewIndexRoute = IncidentsNewIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => IncidentsNewRouteRoute,
} as any);

const StatementsNewStatementRoute = StatementsNewStatementImport.update({
  id: "/statement",
  path: "/statement",
  getParentRoute: () => StatementsNewRouteRoute,
} as any);

const StatementsNewReviewRoute = StatementsNewReviewImport.update({
  id: "/review",
  path: "/review",
  getParentRoute: () => StatementsNewRouteRoute,
} as any);

const StatementsNewDetailsRoute = StatementsNewDetailsImport.update({
  id: "/details",
  path: "/details",
  getParentRoute: () => StatementsNewRouteRoute,
} as any);

const StatementsNewConsentRoute = StatementsNewConsentImport.update({
  id: "/consent",
  path: "/consent",
  getParentRoute: () => StatementsNewRouteRoute,
} as any);

const IncidentsDateIncidentIdRoute = IncidentsDateIncidentIdImport.update({
  id: "/incidents/$date/$incidentId",
  path: "/incidents/$date/$incidentId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/incidents/new": {
      id: "/incidents/new";
      path: "/incidents/new";
      fullPath: "/incidents/new";
      preLoaderRoute: typeof IncidentsNewRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/statements/new": {
      id: "/statements/new";
      path: "/statements/new";
      fullPath: "/statements/new";
      preLoaderRoute: typeof StatementsNewRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/incidents/": {
      id: "/incidents/";
      path: "/incidents";
      fullPath: "/incidents";
      preLoaderRoute: typeof IncidentsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/statements/": {
      id: "/statements/";
      path: "/statements";
      fullPath: "/statements";
      preLoaderRoute: typeof StatementsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/templates/": {
      id: "/templates/";
      path: "/templates";
      fullPath: "/templates";
      preLoaderRoute: typeof TemplatesIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/incidents/$date/$incidentId": {
      id: "/incidents/$date/$incidentId";
      path: "/incidents/$date/$incidentId";
      fullPath: "/incidents/$date/$incidentId";
      preLoaderRoute: typeof IncidentsDateIncidentIdImport;
      parentRoute: typeof rootRoute;
    };
    "/statements/new/consent": {
      id: "/statements/new/consent";
      path: "/consent";
      fullPath: "/statements/new/consent";
      preLoaderRoute: typeof StatementsNewConsentImport;
      parentRoute: typeof StatementsNewRouteImport;
    };
    "/statements/new/details": {
      id: "/statements/new/details";
      path: "/details";
      fullPath: "/statements/new/details";
      preLoaderRoute: typeof StatementsNewDetailsImport;
      parentRoute: typeof StatementsNewRouteImport;
    };
    "/statements/new/review": {
      id: "/statements/new/review";
      path: "/review";
      fullPath: "/statements/new/review";
      preLoaderRoute: typeof StatementsNewReviewImport;
      parentRoute: typeof StatementsNewRouteImport;
    };
    "/statements/new/statement": {
      id: "/statements/new/statement";
      path: "/statement";
      fullPath: "/statements/new/statement";
      preLoaderRoute: typeof StatementsNewStatementImport;
      parentRoute: typeof StatementsNewRouteImport;
    };
    "/incidents/new/": {
      id: "/incidents/new/";
      path: "/";
      fullPath: "/incidents/new/";
      preLoaderRoute: typeof IncidentsNewIndexImport;
      parentRoute: typeof IncidentsNewRouteImport;
    };
    "/statements/new/": {
      id: "/statements/new/";
      path: "/";
      fullPath: "/statements/new/";
      preLoaderRoute: typeof StatementsNewIndexImport;
      parentRoute: typeof StatementsNewRouteImport;
    };
  }
}

// Create and export the route tree

interface IncidentsNewRouteRouteChildren {
  IncidentsNewIndexRoute: typeof IncidentsNewIndexRoute;
}

const IncidentsNewRouteRouteChildren: IncidentsNewRouteRouteChildren = {
  IncidentsNewIndexRoute: IncidentsNewIndexRoute,
};

const IncidentsNewRouteRouteWithChildren =
  IncidentsNewRouteRoute._addFileChildren(IncidentsNewRouteRouteChildren);

interface StatementsNewRouteRouteChildren {
  StatementsNewConsentRoute: typeof StatementsNewConsentRoute;
  StatementsNewDetailsRoute: typeof StatementsNewDetailsRoute;
  StatementsNewReviewRoute: typeof StatementsNewReviewRoute;
  StatementsNewStatementRoute: typeof StatementsNewStatementRoute;
  StatementsNewIndexRoute: typeof StatementsNewIndexRoute;
}

const StatementsNewRouteRouteChildren: StatementsNewRouteRouteChildren = {
  StatementsNewConsentRoute: StatementsNewConsentRoute,
  StatementsNewDetailsRoute: StatementsNewDetailsRoute,
  StatementsNewReviewRoute: StatementsNewReviewRoute,
  StatementsNewStatementRoute: StatementsNewStatementRoute,
  StatementsNewIndexRoute: StatementsNewIndexRoute,
};

const StatementsNewRouteRouteWithChildren =
  StatementsNewRouteRoute._addFileChildren(StatementsNewRouteRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/incidents/new": typeof IncidentsNewRouteRouteWithChildren;
  "/statements/new": typeof StatementsNewRouteRouteWithChildren;
  "/incidents": typeof IncidentsIndexRoute;
  "/statements": typeof StatementsIndexRoute;
  "/templates": typeof TemplatesIndexRoute;
  "/incidents/$date/$incidentId": typeof IncidentsDateIncidentIdRoute;
  "/statements/new/consent": typeof StatementsNewConsentRoute;
  "/statements/new/details": typeof StatementsNewDetailsRoute;
  "/statements/new/review": typeof StatementsNewReviewRoute;
  "/statements/new/statement": typeof StatementsNewStatementRoute;
  "/incidents/new/": typeof IncidentsNewIndexRoute;
  "/statements/new/": typeof StatementsNewIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/incidents": typeof IncidentsIndexRoute;
  "/statements": typeof StatementsIndexRoute;
  "/templates": typeof TemplatesIndexRoute;
  "/incidents/$date/$incidentId": typeof IncidentsDateIncidentIdRoute;
  "/statements/new/consent": typeof StatementsNewConsentRoute;
  "/statements/new/details": typeof StatementsNewDetailsRoute;
  "/statements/new/review": typeof StatementsNewReviewRoute;
  "/statements/new/statement": typeof StatementsNewStatementRoute;
  "/incidents/new": typeof IncidentsNewIndexRoute;
  "/statements/new": typeof StatementsNewIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/incidents/new": typeof IncidentsNewRouteRouteWithChildren;
  "/statements/new": typeof StatementsNewRouteRouteWithChildren;
  "/incidents/": typeof IncidentsIndexRoute;
  "/statements/": typeof StatementsIndexRoute;
  "/templates/": typeof TemplatesIndexRoute;
  "/incidents/$date/$incidentId": typeof IncidentsDateIncidentIdRoute;
  "/statements/new/consent": typeof StatementsNewConsentRoute;
  "/statements/new/details": typeof StatementsNewDetailsRoute;
  "/statements/new/review": typeof StatementsNewReviewRoute;
  "/statements/new/statement": typeof StatementsNewStatementRoute;
  "/incidents/new/": typeof IncidentsNewIndexRoute;
  "/statements/new/": typeof StatementsNewIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/incidents/new"
    | "/statements/new"
    | "/incidents"
    | "/statements"
    | "/templates"
    | "/incidents/$date/$incidentId"
    | "/statements/new/consent"
    | "/statements/new/details"
    | "/statements/new/review"
    | "/statements/new/statement"
    | "/incidents/new/"
    | "/statements/new/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/incidents"
    | "/statements"
    | "/templates"
    | "/incidents/$date/$incidentId"
    | "/statements/new/consent"
    | "/statements/new/details"
    | "/statements/new/review"
    | "/statements/new/statement"
    | "/incidents/new"
    | "/statements/new";
  id:
    | "__root__"
    | "/"
    | "/incidents/new"
    | "/statements/new"
    | "/incidents/"
    | "/statements/"
    | "/templates/"
    | "/incidents/$date/$incidentId"
    | "/statements/new/consent"
    | "/statements/new/details"
    | "/statements/new/review"
    | "/statements/new/statement"
    | "/incidents/new/"
    | "/statements/new/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  IncidentsNewRouteRoute: typeof IncidentsNewRouteRouteWithChildren;
  StatementsNewRouteRoute: typeof StatementsNewRouteRouteWithChildren;
  IncidentsIndexRoute: typeof IncidentsIndexRoute;
  StatementsIndexRoute: typeof StatementsIndexRoute;
  TemplatesIndexRoute: typeof TemplatesIndexRoute;
  IncidentsDateIncidentIdRoute: typeof IncidentsDateIncidentIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsNewRouteRoute: IncidentsNewRouteRouteWithChildren,
  StatementsNewRouteRoute: StatementsNewRouteRouteWithChildren,
  IncidentsIndexRoute: IncidentsIndexRoute,
  StatementsIndexRoute: StatementsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  IncidentsDateIncidentIdRoute: IncidentsDateIncidentIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/incidents/new",
        "/statements/new",
        "/incidents/",
        "/statements/",
        "/templates/",
        "/incidents/$date/$incidentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/incidents/new": {
      "filePath": "incidents/new/route.tsx",
      "children": [
        "/incidents/new/"
      ]
    },
    "/statements/new": {
      "filePath": "statements/new/route.tsx",
      "children": [
        "/statements/new/consent",
        "/statements/new/details",
        "/statements/new/review",
        "/statements/new/statement",
        "/statements/new/"
      ]
    },
    "/incidents/": {
      "filePath": "incidents/index.tsx"
    },
    "/statements/": {
      "filePath": "statements/index.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    },
    "/incidents/$date/$incidentId": {
      "filePath": "incidents/$date/$incidentId.tsx"
    },
    "/statements/new/consent": {
      "filePath": "statements/new/consent.tsx",
      "parent": "/statements/new"
    },
    "/statements/new/details": {
      "filePath": "statements/new/details.tsx",
      "parent": "/statements/new"
    },
    "/statements/new/review": {
      "filePath": "statements/new/review.tsx",
      "parent": "/statements/new"
    },
    "/statements/new/statement": {
      "filePath": "statements/new/statement.tsx",
      "parent": "/statements/new"
    },
    "/incidents/new/": {
      "filePath": "incidents/new/index.tsx",
      "parent": "/incidents/new"
    },
    "/statements/new/": {
      "filePath": "statements/new/index.tsx",
      "parent": "/statements/new"
    }
  }
}
ROUTE_MANIFEST_END */
