/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TemplatesIndexImport } from './routes/templates/index'
import { Route as StatementsIndexImport } from './routes/statements/index'
import { Route as IncidentsIndexImport } from './routes/incidents/index'
import { Route as TemplatesNewImport } from './routes/templates/new'
import { Route as TemplatesTemplateIdImport } from './routes/templates/$templateId'
import { Route as StatementsNewImport } from './routes/statements/new'
import { Route as StatementsStatementIdRouteImport } from './routes/statements/$statementId/route'
import { Route as IncidentsNewRouteImport } from './routes/incidents/new/route'
import { Route as IncidentsNewIndexImport } from './routes/incidents/new/index'
import { Route as StatementsStatementIdStatementImport } from './routes/statements/$statementId/statement'
import { Route as StatementsStatementIdReviewImport } from './routes/statements/$statementId/review'
import { Route as StatementsStatementIdDetailsImport } from './routes/statements/$statementId/details'
import { Route as StatementsStatementIdConsentImport } from './routes/statements/$statementId/consent'
import { Route as IncidentsDateIncidentIdRouteImport } from './routes/incidents/$date/$incidentId/route'
import { Route as IncidentsDateIncidentIdOverviewImport } from './routes/incidents/$date/$incidentId/overview'
import { Route as IncidentsDateIncidentIdImportImport } from './routes/incidents/$date/$incidentId/import'
import { Route as IncidentsDateIncidentIdExportImport } from './routes/incidents/$date/$incidentId/export'
import { Route as IncidentsDateIncidentIdDetsImport } from './routes/incidents/$date/$incidentId/dets'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesIndexRoute = TemplatesIndexImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRoute,
} as any)

const StatementsIndexRoute = StatementsIndexImport.update({
  id: '/statements/',
  path: '/statements/',
  getParentRoute: () => rootRoute,
} as any)

const IncidentsIndexRoute = IncidentsIndexImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesNewRoute = TemplatesNewImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesTemplateIdRoute = TemplatesTemplateIdImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRoute,
} as any)

const StatementsNewRoute = StatementsNewImport.update({
  id: '/statements/new',
  path: '/statements/new',
  getParentRoute: () => rootRoute,
} as any)

const StatementsStatementIdRouteRoute = StatementsStatementIdRouteImport.update(
  {
    id: '/statements/$statementId',
    path: '/statements/$statementId',
    getParentRoute: () => rootRoute,
  } as any,
)

const IncidentsNewRouteRoute = IncidentsNewRouteImport.update({
  id: '/incidents/new',
  path: '/incidents/new',
  getParentRoute: () => rootRoute,
} as any)

const IncidentsNewIndexRoute = IncidentsNewIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncidentsNewRouteRoute,
} as any)

const StatementsStatementIdStatementRoute =
  StatementsStatementIdStatementImport.update({
    id: '/statement',
    path: '/statement',
    getParentRoute: () => StatementsStatementIdRouteRoute,
  } as any)

const StatementsStatementIdReviewRoute =
  StatementsStatementIdReviewImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => StatementsStatementIdRouteRoute,
  } as any)

const StatementsStatementIdDetailsRoute =
  StatementsStatementIdDetailsImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => StatementsStatementIdRouteRoute,
  } as any)

const StatementsStatementIdConsentRoute =
  StatementsStatementIdConsentImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => StatementsStatementIdRouteRoute,
  } as any)

const IncidentsDateIncidentIdRouteRoute =
  IncidentsDateIncidentIdRouteImport.update({
    id: '/incidents/$date/$incidentId',
    path: '/incidents/$date/$incidentId',
    getParentRoute: () => rootRoute,
  } as any)

const IncidentsDateIncidentIdOverviewRoute =
  IncidentsDateIncidentIdOverviewImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => IncidentsDateIncidentIdRouteRoute,
  } as any)

const IncidentsDateIncidentIdImportRoute =
  IncidentsDateIncidentIdImportImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => IncidentsDateIncidentIdRouteRoute,
  } as any)

const IncidentsDateIncidentIdExportRoute =
  IncidentsDateIncidentIdExportImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => IncidentsDateIncidentIdRouteRoute,
  } as any)

const IncidentsDateIncidentIdDetsRoute =
  IncidentsDateIncidentIdDetsImport.update({
    id: '/dets',
    path: '/dets',
    getParentRoute: () => IncidentsDateIncidentIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/incidents/new': {
      id: '/incidents/new'
      path: '/incidents/new'
      fullPath: '/incidents/new'
      preLoaderRoute: typeof IncidentsNewRouteImport
      parentRoute: typeof rootRoute
    }
    '/statements/$statementId': {
      id: '/statements/$statementId'
      path: '/statements/$statementId'
      fullPath: '/statements/$statementId'
      preLoaderRoute: typeof StatementsStatementIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/statements/new': {
      id: '/statements/new'
      path: '/statements/new'
      fullPath: '/statements/new'
      preLoaderRoute: typeof StatementsNewImport
      parentRoute: typeof rootRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdImport
      parentRoute: typeof rootRoute
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewImport
      parentRoute: typeof rootRoute
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/statements/': {
      id: '/statements/'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsIndexImport
      parentRoute: typeof rootRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/incidents/$date/$incidentId': {
      id: '/incidents/$date/$incidentId'
      path: '/incidents/$date/$incidentId'
      fullPath: '/incidents/$date/$incidentId'
      preLoaderRoute: typeof IncidentsDateIncidentIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/statements/$statementId/consent': {
      id: '/statements/$statementId/consent'
      path: '/consent'
      fullPath: '/statements/$statementId/consent'
      preLoaderRoute: typeof StatementsStatementIdConsentImport
      parentRoute: typeof StatementsStatementIdRouteImport
    }
    '/statements/$statementId/details': {
      id: '/statements/$statementId/details'
      path: '/details'
      fullPath: '/statements/$statementId/details'
      preLoaderRoute: typeof StatementsStatementIdDetailsImport
      parentRoute: typeof StatementsStatementIdRouteImport
    }
    '/statements/$statementId/review': {
      id: '/statements/$statementId/review'
      path: '/review'
      fullPath: '/statements/$statementId/review'
      preLoaderRoute: typeof StatementsStatementIdReviewImport
      parentRoute: typeof StatementsStatementIdRouteImport
    }
    '/statements/$statementId/statement': {
      id: '/statements/$statementId/statement'
      path: '/statement'
      fullPath: '/statements/$statementId/statement'
      preLoaderRoute: typeof StatementsStatementIdStatementImport
      parentRoute: typeof StatementsStatementIdRouteImport
    }
    '/incidents/new/': {
      id: '/incidents/new/'
      path: '/'
      fullPath: '/incidents/new/'
      preLoaderRoute: typeof IncidentsNewIndexImport
      parentRoute: typeof IncidentsNewRouteImport
    }
    '/incidents/$date/$incidentId/dets': {
      id: '/incidents/$date/$incidentId/dets'
      path: '/dets'
      fullPath: '/incidents/$date/$incidentId/dets'
      preLoaderRoute: typeof IncidentsDateIncidentIdDetsImport
      parentRoute: typeof IncidentsDateIncidentIdRouteImport
    }
    '/incidents/$date/$incidentId/export': {
      id: '/incidents/$date/$incidentId/export'
      path: '/export'
      fullPath: '/incidents/$date/$incidentId/export'
      preLoaderRoute: typeof IncidentsDateIncidentIdExportImport
      parentRoute: typeof IncidentsDateIncidentIdRouteImport
    }
    '/incidents/$date/$incidentId/import': {
      id: '/incidents/$date/$incidentId/import'
      path: '/import'
      fullPath: '/incidents/$date/$incidentId/import'
      preLoaderRoute: typeof IncidentsDateIncidentIdImportImport
      parentRoute: typeof IncidentsDateIncidentIdRouteImport
    }
    '/incidents/$date/$incidentId/overview': {
      id: '/incidents/$date/$incidentId/overview'
      path: '/overview'
      fullPath: '/incidents/$date/$incidentId/overview'
      preLoaderRoute: typeof IncidentsDateIncidentIdOverviewImport
      parentRoute: typeof IncidentsDateIncidentIdRouteImport
    }
  }
}

// Create and export the route tree

interface IncidentsNewRouteRouteChildren {
  IncidentsNewIndexRoute: typeof IncidentsNewIndexRoute
}

const IncidentsNewRouteRouteChildren: IncidentsNewRouteRouteChildren = {
  IncidentsNewIndexRoute: IncidentsNewIndexRoute,
}

const IncidentsNewRouteRouteWithChildren =
  IncidentsNewRouteRoute._addFileChildren(IncidentsNewRouteRouteChildren)

interface StatementsStatementIdRouteRouteChildren {
  StatementsStatementIdConsentRoute: typeof StatementsStatementIdConsentRoute
  StatementsStatementIdDetailsRoute: typeof StatementsStatementIdDetailsRoute
  StatementsStatementIdReviewRoute: typeof StatementsStatementIdReviewRoute
  StatementsStatementIdStatementRoute: typeof StatementsStatementIdStatementRoute
}

const StatementsStatementIdRouteRouteChildren: StatementsStatementIdRouteRouteChildren =
  {
    StatementsStatementIdConsentRoute: StatementsStatementIdConsentRoute,
    StatementsStatementIdDetailsRoute: StatementsStatementIdDetailsRoute,
    StatementsStatementIdReviewRoute: StatementsStatementIdReviewRoute,
    StatementsStatementIdStatementRoute: StatementsStatementIdStatementRoute,
  }

const StatementsStatementIdRouteRouteWithChildren =
  StatementsStatementIdRouteRoute._addFileChildren(
    StatementsStatementIdRouteRouteChildren,
  )

interface IncidentsDateIncidentIdRouteRouteChildren {
  IncidentsDateIncidentIdDetsRoute: typeof IncidentsDateIncidentIdDetsRoute
  IncidentsDateIncidentIdExportRoute: typeof IncidentsDateIncidentIdExportRoute
  IncidentsDateIncidentIdImportRoute: typeof IncidentsDateIncidentIdImportRoute
  IncidentsDateIncidentIdOverviewRoute: typeof IncidentsDateIncidentIdOverviewRoute
}

const IncidentsDateIncidentIdRouteRouteChildren: IncidentsDateIncidentIdRouteRouteChildren =
  {
    IncidentsDateIncidentIdDetsRoute: IncidentsDateIncidentIdDetsRoute,
    IncidentsDateIncidentIdExportRoute: IncidentsDateIncidentIdExportRoute,
    IncidentsDateIncidentIdImportRoute: IncidentsDateIncidentIdImportRoute,
    IncidentsDateIncidentIdOverviewRoute: IncidentsDateIncidentIdOverviewRoute,
  }

const IncidentsDateIncidentIdRouteRouteWithChildren =
  IncidentsDateIncidentIdRouteRoute._addFileChildren(
    IncidentsDateIncidentIdRouteRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents/new': typeof IncidentsNewRouteRouteWithChildren
  '/statements/$statementId': typeof StatementsStatementIdRouteRouteWithChildren
  '/statements/new': typeof StatementsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/incidents': typeof IncidentsIndexRoute
  '/statements': typeof StatementsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/incidents/$date/$incidentId': typeof IncidentsDateIncidentIdRouteRouteWithChildren
  '/statements/$statementId/consent': typeof StatementsStatementIdConsentRoute
  '/statements/$statementId/details': typeof StatementsStatementIdDetailsRoute
  '/statements/$statementId/review': typeof StatementsStatementIdReviewRoute
  '/statements/$statementId/statement': typeof StatementsStatementIdStatementRoute
  '/incidents/new/': typeof IncidentsNewIndexRoute
  '/incidents/$date/$incidentId/dets': typeof IncidentsDateIncidentIdDetsRoute
  '/incidents/$date/$incidentId/export': typeof IncidentsDateIncidentIdExportRoute
  '/incidents/$date/$incidentId/import': typeof IncidentsDateIncidentIdImportRoute
  '/incidents/$date/$incidentId/overview': typeof IncidentsDateIncidentIdOverviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/statements/$statementId': typeof StatementsStatementIdRouteRouteWithChildren
  '/statements/new': typeof StatementsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/incidents': typeof IncidentsIndexRoute
  '/statements': typeof StatementsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/incidents/$date/$incidentId': typeof IncidentsDateIncidentIdRouteRouteWithChildren
  '/statements/$statementId/consent': typeof StatementsStatementIdConsentRoute
  '/statements/$statementId/details': typeof StatementsStatementIdDetailsRoute
  '/statements/$statementId/review': typeof StatementsStatementIdReviewRoute
  '/statements/$statementId/statement': typeof StatementsStatementIdStatementRoute
  '/incidents/new': typeof IncidentsNewIndexRoute
  '/incidents/$date/$incidentId/dets': typeof IncidentsDateIncidentIdDetsRoute
  '/incidents/$date/$incidentId/export': typeof IncidentsDateIncidentIdExportRoute
  '/incidents/$date/$incidentId/import': typeof IncidentsDateIncidentIdImportRoute
  '/incidents/$date/$incidentId/overview': typeof IncidentsDateIncidentIdOverviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/incidents/new': typeof IncidentsNewRouteRouteWithChildren
  '/statements/$statementId': typeof StatementsStatementIdRouteRouteWithChildren
  '/statements/new': typeof StatementsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/statements/': typeof StatementsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/incidents/$date/$incidentId': typeof IncidentsDateIncidentIdRouteRouteWithChildren
  '/statements/$statementId/consent': typeof StatementsStatementIdConsentRoute
  '/statements/$statementId/details': typeof StatementsStatementIdDetailsRoute
  '/statements/$statementId/review': typeof StatementsStatementIdReviewRoute
  '/statements/$statementId/statement': typeof StatementsStatementIdStatementRoute
  '/incidents/new/': typeof IncidentsNewIndexRoute
  '/incidents/$date/$incidentId/dets': typeof IncidentsDateIncidentIdDetsRoute
  '/incidents/$date/$incidentId/export': typeof IncidentsDateIncidentIdExportRoute
  '/incidents/$date/$incidentId/import': typeof IncidentsDateIncidentIdImportRoute
  '/incidents/$date/$incidentId/overview': typeof IncidentsDateIncidentIdOverviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incidents/new'
    | '/statements/$statementId'
    | '/statements/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/incidents'
    | '/statements'
    | '/templates'
    | '/incidents/$date/$incidentId'
    | '/statements/$statementId/consent'
    | '/statements/$statementId/details'
    | '/statements/$statementId/review'
    | '/statements/$statementId/statement'
    | '/incidents/new/'
    | '/incidents/$date/$incidentId/dets'
    | '/incidents/$date/$incidentId/export'
    | '/incidents/$date/$incidentId/import'
    | '/incidents/$date/$incidentId/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/statements/$statementId'
    | '/statements/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/incidents'
    | '/statements'
    | '/templates'
    | '/incidents/$date/$incidentId'
    | '/statements/$statementId/consent'
    | '/statements/$statementId/details'
    | '/statements/$statementId/review'
    | '/statements/$statementId/statement'
    | '/incidents/new'
    | '/incidents/$date/$incidentId/dets'
    | '/incidents/$date/$incidentId/export'
    | '/incidents/$date/$incidentId/import'
    | '/incidents/$date/$incidentId/overview'
  id:
    | '__root__'
    | '/'
    | '/incidents/new'
    | '/statements/$statementId'
    | '/statements/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/incidents/'
    | '/statements/'
    | '/templates/'
    | '/incidents/$date/$incidentId'
    | '/statements/$statementId/consent'
    | '/statements/$statementId/details'
    | '/statements/$statementId/review'
    | '/statements/$statementId/statement'
    | '/incidents/new/'
    | '/incidents/$date/$incidentId/dets'
    | '/incidents/$date/$incidentId/export'
    | '/incidents/$date/$incidentId/import'
    | '/incidents/$date/$incidentId/overview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsNewRouteRoute: typeof IncidentsNewRouteRouteWithChildren
  StatementsStatementIdRouteRoute: typeof StatementsStatementIdRouteRouteWithChildren
  StatementsNewRoute: typeof StatementsNewRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  StatementsIndexRoute: typeof StatementsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  IncidentsDateIncidentIdRouteRoute: typeof IncidentsDateIncidentIdRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsNewRouteRoute: IncidentsNewRouteRouteWithChildren,
  StatementsStatementIdRouteRoute: StatementsStatementIdRouteRouteWithChildren,
  StatementsNewRoute: StatementsNewRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  StatementsIndexRoute: StatementsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  IncidentsDateIncidentIdRouteRoute:
    IncidentsDateIncidentIdRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/incidents/new",
        "/statements/$statementId",
        "/statements/new",
        "/templates/$templateId",
        "/templates/new",
        "/incidents/",
        "/statements/",
        "/templates/",
        "/incidents/$date/$incidentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/incidents/new": {
      "filePath": "incidents/new/route.tsx",
      "children": [
        "/incidents/new/"
      ]
    },
    "/statements/$statementId": {
      "filePath": "statements/$statementId/route.tsx",
      "children": [
        "/statements/$statementId/consent",
        "/statements/$statementId/details",
        "/statements/$statementId/review",
        "/statements/$statementId/statement"
      ]
    },
    "/statements/new": {
      "filePath": "statements/new.tsx"
    },
    "/templates/$templateId": {
      "filePath": "templates/$templateId.tsx"
    },
    "/templates/new": {
      "filePath": "templates/new.tsx"
    },
    "/incidents/": {
      "filePath": "incidents/index.tsx"
    },
    "/statements/": {
      "filePath": "statements/index.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    },
    "/incidents/$date/$incidentId": {
      "filePath": "incidents/$date/$incidentId/route.tsx",
      "children": [
        "/incidents/$date/$incidentId/dets",
        "/incidents/$date/$incidentId/export",
        "/incidents/$date/$incidentId/import",
        "/incidents/$date/$incidentId/overview"
      ]
    },
    "/statements/$statementId/consent": {
      "filePath": "statements/$statementId/consent.tsx",
      "parent": "/statements/$statementId"
    },
    "/statements/$statementId/details": {
      "filePath": "statements/$statementId/details.tsx",
      "parent": "/statements/$statementId"
    },
    "/statements/$statementId/review": {
      "filePath": "statements/$statementId/review.tsx",
      "parent": "/statements/$statementId"
    },
    "/statements/$statementId/statement": {
      "filePath": "statements/$statementId/statement.tsx",
      "parent": "/statements/$statementId"
    },
    "/incidents/new/": {
      "filePath": "incidents/new/index.tsx",
      "parent": "/incidents/new"
    },
    "/incidents/$date/$incidentId/dets": {
      "filePath": "incidents/$date/$incidentId/dets.tsx",
      "parent": "/incidents/$date/$incidentId"
    },
    "/incidents/$date/$incidentId/export": {
      "filePath": "incidents/$date/$incidentId/export.tsx",
      "parent": "/incidents/$date/$incidentId"
    },
    "/incidents/$date/$incidentId/import": {
      "filePath": "incidents/$date/$incidentId/import.tsx",
      "parent": "/incidents/$date/$incidentId"
    },
    "/incidents/$date/$incidentId/overview": {
      "filePath": "incidents/$date/$incidentId/overview.tsx",
      "parent": "/incidents/$date/$incidentId"
    }
  }
}
ROUTE_MANIFEST_END */
