/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TemplatesIndexImport } from './routes/templates/index'
import { Route as DocumentsIndexImport } from './routes/documents/index'
import { Route as DocumentsNewRouteImport } from './routes/documents/new/route'
import { Route as DocumentsNewIndexImport } from './routes/documents/new/index'
import { Route as DocumentsNewStatementImport } from './routes/documents/new/statement'
import { Route as DocumentsNewReviewImport } from './routes/documents/new/review'
import { Route as DocumentsNewDetailsImport } from './routes/documents/new/details'
import { Route as DocumentsNewConsentImport } from './routes/documents/new/consent'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesIndexRoute = TemplatesIndexImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentsIndexRoute = DocumentsIndexImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentsNewRouteRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRoute,
} as any)

const DocumentsNewIndexRoute = DocumentsNewIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsNewRouteRoute,
} as any)

const DocumentsNewStatementRoute = DocumentsNewStatementImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => DocumentsNewRouteRoute,
} as any)

const DocumentsNewReviewRoute = DocumentsNewReviewImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DocumentsNewRouteRoute,
} as any)

const DocumentsNewDetailsRoute = DocumentsNewDetailsImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => DocumentsNewRouteRoute,
} as any)

const DocumentsNewConsentRoute = DocumentsNewConsentImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => DocumentsNewRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/documents/new/consent': {
      id: '/documents/new/consent'
      path: '/consent'
      fullPath: '/documents/new/consent'
      preLoaderRoute: typeof DocumentsNewConsentImport
      parentRoute: typeof DocumentsNewRouteImport
    }
    '/documents/new/details': {
      id: '/documents/new/details'
      path: '/details'
      fullPath: '/documents/new/details'
      preLoaderRoute: typeof DocumentsNewDetailsImport
      parentRoute: typeof DocumentsNewRouteImport
    }
    '/documents/new/review': {
      id: '/documents/new/review'
      path: '/review'
      fullPath: '/documents/new/review'
      preLoaderRoute: typeof DocumentsNewReviewImport
      parentRoute: typeof DocumentsNewRouteImport
    }
    '/documents/new/statement': {
      id: '/documents/new/statement'
      path: '/statement'
      fullPath: '/documents/new/statement'
      preLoaderRoute: typeof DocumentsNewStatementImport
      parentRoute: typeof DocumentsNewRouteImport
    }
    '/documents/new/': {
      id: '/documents/new/'
      path: '/'
      fullPath: '/documents/new/'
      preLoaderRoute: typeof DocumentsNewIndexImport
      parentRoute: typeof DocumentsNewRouteImport
    }
  }
}

// Create and export the route tree

interface DocumentsNewRouteRouteChildren {
  DocumentsNewConsentRoute: typeof DocumentsNewConsentRoute
  DocumentsNewDetailsRoute: typeof DocumentsNewDetailsRoute
  DocumentsNewReviewRoute: typeof DocumentsNewReviewRoute
  DocumentsNewStatementRoute: typeof DocumentsNewStatementRoute
  DocumentsNewIndexRoute: typeof DocumentsNewIndexRoute
}

const DocumentsNewRouteRouteChildren: DocumentsNewRouteRouteChildren = {
  DocumentsNewConsentRoute: DocumentsNewConsentRoute,
  DocumentsNewDetailsRoute: DocumentsNewDetailsRoute,
  DocumentsNewReviewRoute: DocumentsNewReviewRoute,
  DocumentsNewStatementRoute: DocumentsNewStatementRoute,
  DocumentsNewIndexRoute: DocumentsNewIndexRoute,
}

const DocumentsNewRouteRouteWithChildren =
  DocumentsNewRouteRoute._addFileChildren(DocumentsNewRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents/new': typeof DocumentsNewRouteRouteWithChildren
  '/documents': typeof DocumentsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/documents/new/consent': typeof DocumentsNewConsentRoute
  '/documents/new/details': typeof DocumentsNewDetailsRoute
  '/documents/new/review': typeof DocumentsNewReviewRoute
  '/documents/new/statement': typeof DocumentsNewStatementRoute
  '/documents/new/': typeof DocumentsNewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/documents/new/consent': typeof DocumentsNewConsentRoute
  '/documents/new/details': typeof DocumentsNewDetailsRoute
  '/documents/new/review': typeof DocumentsNewReviewRoute
  '/documents/new/statement': typeof DocumentsNewStatementRoute
  '/documents/new': typeof DocumentsNewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/documents/new': typeof DocumentsNewRouteRouteWithChildren
  '/documents/': typeof DocumentsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/documents/new/consent': typeof DocumentsNewConsentRoute
  '/documents/new/details': typeof DocumentsNewDetailsRoute
  '/documents/new/review': typeof DocumentsNewReviewRoute
  '/documents/new/statement': typeof DocumentsNewStatementRoute
  '/documents/new/': typeof DocumentsNewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents/new'
    | '/documents'
    | '/templates'
    | '/documents/new/consent'
    | '/documents/new/details'
    | '/documents/new/review'
    | '/documents/new/statement'
    | '/documents/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/templates'
    | '/documents/new/consent'
    | '/documents/new/details'
    | '/documents/new/review'
    | '/documents/new/statement'
    | '/documents/new'
  id:
    | '__root__'
    | '/'
    | '/documents/new'
    | '/documents/'
    | '/templates/'
    | '/documents/new/consent'
    | '/documents/new/details'
    | '/documents/new/review'
    | '/documents/new/statement'
    | '/documents/new/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsNewRouteRoute: typeof DocumentsNewRouteRouteWithChildren
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsNewRouteRoute: DocumentsNewRouteRouteWithChildren,
  DocumentsIndexRoute: DocumentsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/documents/new",
        "/documents/",
        "/templates/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/documents/new": {
      "filePath": "documents/new/route.tsx",
      "children": [
        "/documents/new/consent",
        "/documents/new/details",
        "/documents/new/review",
        "/documents/new/statement",
        "/documents/new/"
      ]
    },
    "/documents/": {
      "filePath": "documents/index.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    },
    "/documents/new/consent": {
      "filePath": "documents/new/consent.tsx",
      "parent": "/documents/new"
    },
    "/documents/new/details": {
      "filePath": "documents/new/details.tsx",
      "parent": "/documents/new"
    },
    "/documents/new/review": {
      "filePath": "documents/new/review.tsx",
      "parent": "/documents/new"
    },
    "/documents/new/statement": {
      "filePath": "documents/new/statement.tsx",
      "parent": "/documents/new"
    },
    "/documents/new/": {
      "filePath": "documents/new/index.tsx",
      "parent": "/documents/new"
    }
  }
}
ROUTE_MANIFEST_END */
